---
- name: update all packages
  yum: name=* state=latest

- name: Install packages
  yum:
    name: 
      - gcc
      - gcc-c++
      - openssl-devel 
      - readline-devel 
      - zlib-devel
      - git
      - ruby-devel
    state: present